### ISSUE TITLE
[1.16.5] Crash when placing first block with ListCommand

### ISSUE THREAD

**Issue by rrehbein** [McJty/McJtyLib#142]
Game crashes when placing the first block with a ServerCommand/ListCommand annotation. Reloading the world and placing a 2nd does not trigger the error.

Steps:
1. Create new world
2. Grab a Matter Receiver
3. Place it
4. Crash

Actual:
```

[08:54:10] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 9475143e-7dea-4fed-a9fe-c3991a1aa40d
[08:54:10] [Render thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalStateException: The command 'rftoolsutility.receiver.getPlayers' is already registered!
	at mcjty.lib.McJtyLib.registerListCommandInfo(McJtyLib.java:67) ~[mcjtylib:1.16-5.1.0.30] {re:classloading}
```

Logs generating using a modified version of the library.

```diff
diff --git a/src/main/java/mcjty/lib/McJtyLib.java b/src/main/java/mcjty/lib/McJtyLib.java
index b7009a9f..15134a39 100644
--- a/src/main/java/mcjty/lib/McJtyLib.java
+++ b/src/main/java/mcjty/lib/McJtyLib.java
@@ -63,6 +63,7 @@ public class McJtyLib {
      * an associated type parameter
      */
     public static <T> void registerListCommandInfo(String command, Class<T> type, Function<PacketBuffer, T> deserializer, BiConsumer<PacketBuffer, T> serializer) {
+        mcjty.lib.McJtyLib.setup.getLogger().info("Registering list command: "+command);
         if (commandInfos.containsKey(command)) {
             throw new IllegalStateException(("The command '" + command + "' is already registered!"));
         }
@@ -77,10 +78,12 @@ public class McJtyLib {
      * Used in combination with PacketSendServerCommand for a more global command
      */
     public static void registerCommand(String modid, String id, IServerCommand command) {
+        mcjty.lib.McJtyLib.setup.getLogger().info("Registering server command: "+command);
         serverCommands.put(Pair.of(modid, id), command);
     }
 
     public static void registerClientCommand(String modid, String id, IServerCommand command) {
+        mcjty.lib.McJtyLib.setup.getLogger().info("Registering client command: "+command);
         clientCommands.put(Pair.of(modid, id), command);
     }
 
```

Logs:
[latest.log](https://github.com/McJtyMods/McJtyLib/files/7661555/latest.log)

Mod List: 

- forge-1.16.5-36.2.0-client.jar
- forge-1.16.5-36.2.0-universal.jar
- mcjtylib-1.16-5.1.1.jar (built from git) and repeatable with mcjtylib-1.16-5.1.0.30.jar 
- rftoolsbase-1.16-2.1.0.jar (built from git)
- rftoolsutility-1.16-3.1.5.jar (built from git)

**Comment by rrehbein** [comment]
Unable to replicate with CurseForge version of mod list.
Unable to replicate with other mods using ListCommand, eg: rftoolsdim.

**Comment by dav20011** [comment]
I am able to replicate this issue with the same versions from CurseForge. The MatterReceiver is fine, but it happens with the MatterTransmitter:

```
java.lang.IllegalStateException: The command 'rftoolsutility.transmitter.getPlayers' is already registered!
	at mcjty.lib.McJtyLib.registerListCommandInfo(McJtyLib.java:67) ~[?:1.16-5.1.1]
	at mcjty.lib.tileentity.AnnotationTools.scanServerCommands(AnnotationTools.java:62) ~[?:1.16-5.1.1]
	at mcjty.lib.tileentity.AnnotationTools.createAnnotationHolder(AnnotationTools.java:27) ~[?:1.16-5.1.1]
	at mcjty.lib.tileentity.GenericTileEntity.getAnnotationHolder(GenericTileEntity.java:676) ~[?:1.16-5.1.1]
	at mcjty.lib.tileentity.GenericTileEntity.<init>(GenericTileEntity.java:77) ~[?:1.16-5.1.1]
	at mcjty.rftoolsutility.modules.teleporter.blocks.MatterTransmitterTileEntity.<init>(MatterTransmitterTileEntity.java:105) ~[?:1.16-3.1.5]
	at mcjty.rftoolsutility.modules.teleporter.blocks.MatterTransmitterBlock$$Lambda$4271/2133668271.get(Unknown Source) ~[?:?]
	at mcjty.lib.blocks.BaseBlock.createTileEntity(BaseBlock.java:354) ~[?:1.16-5.1.1]
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:120) ~[?:?]
```

It does not crash the game but prevents the instantiation of the tile entity, so the block is not very useful. Apart from that the issue is just like described above. After restarting the game it works fine and placing further tranmitters does not trigger it again.

**Comment by rrehbein** [comment]
Using mod versions from CurseForge, I get a mix of error-no-crash and crash.

- Matter Receiver - error
- Matter Transmitter - error
- Dialing Device - crash
- Dimlet Workbench - crash
- Endergenic - no error

Oddly I wasn't getting this combination when on discord with McJty. However I was so focused on the crash part of my report I didn't look for errors without a crash.

**Comment by McJty** [comment]
Well I haven't gotten any other reports and I can't reproduce it myself. Also the crash doesn't make sense. So there is really not much I can do about this

**Comment by dav20011** [comment]
The issue is very random to say the least. I tried doing exactly the same thing 5 times and every time something else happened. Maybe some more details help:

* System: Windows 10 21H1
* Create a new 1.16.5 Instance with Curse and the default Forge version and use the integrated Java
* Install just RFTools Utility via Curse so it installs all of the necessary mods automatically
* Start and create a new world in creative
* Take the Matter Transmitter, Receiver and Dialing Device from the creative menu (from left to right in the menu)
* Place the blocks in the opposite order

With this procedure most of the time the game either crashed or one of the blocks had the error without a crash (-> GUI does not open). It only worked correctly for a single time.

**Comment by McJty** [comment]
I think I partially understand why this can occur and it's normal. So I will just remove the test
